version: '3.8'
services:
  mysql.modbusparser.work:
    image: mysql
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: tuf
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    tty: true
    stdin_open: true
    networks:
      - modbusparser
  backend:
    image: ${DOCKER_USER}/modbus-backend:${CIRCLE_SHA1}
    restart: always
    ports:
      - 8080:8080
    networks:
      - modbusparser
  frontend:
    image: ${DOCKER_USER}/modbus-frontend:${CIRCLE_SHA1}
    ports:
      - 80:80
    networks:
      - modbusparser
networks:
  modbusparser:
    name: modbusparser
